#!/bin/sh
# $Id$
unixtime=`misc/utc`
if cvs commit "$@"; then
  if echo "#define CVSBUILD ${unixtime}			/* utc unixtime of cvs commit */" > src/build.h; then
	echo "Updated build stamp to: ${unixtime}"
	echo "Commiting new build.h"
	cvs commit src/build.h -m "Build stamp"
   else
	echo "Failed to update timestamp, bailing out."
	exit
   fi
fi

