#!/bin/sh
# $Id$
utctime="./utctime"
if ! test -f "$utctime"; then
  gcc -Wall -O2 -o utctime src/utc-time.c
fi
if cvs commit "$@"; then
  unixtime=`${utctime}`
  if echo "#define CVSBUILD ${unixtime}			/* utc unixtime of cvs commit */" > src/build.h; then
	echo "Updated build stamp to: ${unixtime}"
	echo "Commiting new build.h"
	cvs commit -m "Build stamp (Automatic)" src/build.h
   else
	echo "Failed to update timestamp, bailing out."
	exit 1 
   fi
fi
rm ${utctime}
